### ISSUE TITLE
2018/05 - PyDays Vienna

### ISSUE THREAD

**Issue by warenlg** [src-d/conferences#59] opened 2018-03-27 10:33 UTC
**URL**: https://pyvie2018.gitlab.io/

**Location**: Vienna, Austria

**Dates**: 2018/05/04-05

**Expenses covered**: no

**Topic**: Python, GitHub, programming languages

**Call for Papers**:

deadline: 2018/03/25
link: lhttps://www.pydays.at/cfp/

**Notes**:

**Comment by vmarkovtsev** [comment] 2018-04-03 12:15
Duplicate of #54

**Closed as completed by vmarkovtsev** 2018-04-03 12:15 UTC
