### ISSUE TITLE
2018/11 - DevFest Krasnodar

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#89] opened 2018-08-29 10:12 UTC
**URL**: https://www.meetup.com/meetup-group-IfBrKrSH/events/253269181/

**Location**: Krasnodar, Russia

**Dates**: 2018/11/17

**Expenses covered**: Google pays for everything if you are a GDE

**Topic**: Google tech

**Call for Papers**:

deadline: N/A
link: N/A

**Notes**:

Contacted privately by the organizers. Estimated attendance: 450.

**Comment by vcoisne** [comment] 2018-09-04 21:52
@vmarkovtsev looks like 450 is the total capacity, the group only has 288 members so I don't think turn out will be great.

**Comment by vmarkovtsev** [comment] 2018-09-05 06:52
There will be people from the outside of the group since these events are rare in that region.

**Comment by vcoisne** [comment] 2018-09-25 23:05
Is this confirmed @vmarkovtsev ?

**Comment by vmarkovtsev** [comment] 2018-09-26 08:07
Confirmed and paid by Google.

**Comment by vcoisne** [comment] 2018-12-22 00:08
@vmarkovtsev was that the same slides as the other DevFest on tensorflow.js ? Want to submit a PR so that we can close this issue ?

**Comment by campoy** [comment] 2019-01-10 01:41
ping

**Comment by vmarkovtsev** [comment] 2019-01-10 10:48
The PR has already been merged https://github.com/src-d/conferences/pull/93 and we can close.

**Comment by vcoisne** [comment] 2019-01-10 19:18
Closing.

**Closed as completed by vcoisne** 2019-01-10 19:18 UTC
Labels: phase:accepted
